# Generated by Django 2.1.1 on 2018-09-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='npages',
            field=models.IntegerField(default=None),
        ),
    ]
