# Generated by Django 2.1.1 on 2018-09-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_auto_20180925_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='npages',
        ),
    ]
